export type ZenRouteKind = "responses" | "messages" | "chat_completions" | "model_specific";
export type ZenApiFormat = "openai" | "anthropic";

export interface ZenModelInfo {
  id: string;
  requestModelId: string;
  name: string;
  displayName: string;
  routeKind: ZenRouteKind;
  apiFormat: ZenApiFormat;
  contextWindow: number;
  maxOutput: number;
  supportsTools: boolean;
  supportsVision: boolean;
  fixedTemperature?: number;
  supportsThinking?: boolean;
  needsReasoningContentWorkaround?: boolean;
}

// Models that do not actually support tool/function calling.
// These still declare toolCalling capability so they appear in the model picker,
// but the provider strips tools from requests before sending to the API.
export const NO_TOOL_MODEL_IDS = new Set([
  "big-pickle",
  "deepseek-v4-flash-free",
  "hy3-free",
  "laguna-s-2.1-free",
  "mimo-v2.5-free",
  "nemotron-3-ultra-free",
  "nemotron-3.5-lightning-free",
]);

export const ZEN_MODEL_CATALOG: ZenModelInfo[] = [
  {
    id: "big-pickle",
    requestModelId: "big-pickle",
    name: "Big Pickle",
    displayName: "Big Pickle",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "claude-fable-5",
    requestModelId: "claude-fable-5",
    name: "Claude Fable 5",
    displayName: "Claude Fable 5",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-haiku-4-5",
    requestModelId: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    displayName: "Claude Haiku 4.5",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-opus-4-5",
    requestModelId: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    displayName: "Claude Opus 4.5",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-opus-4-6",
    requestModelId: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    displayName: "Claude Opus 4.6",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-opus-4-7",
    requestModelId: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    displayName: "Claude Opus 4.7",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-opus-4-8",
    requestModelId: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    displayName: "Claude Opus 4.8",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-opus-5",
    requestModelId: "claude-opus-5",
    name: "Claude Opus 5",
    displayName: "Claude Opus 5",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-sonnet-4",
    requestModelId: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    displayName: "Claude Sonnet 4",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-sonnet-4-5",
    requestModelId: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    displayName: "Claude Sonnet 4.5",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-sonnet-4-6",
    requestModelId: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    displayName: "Claude Sonnet 4.6",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "claude-sonnet-5",
    requestModelId: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    displayName: "Claude Sonnet 5",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "deepseek-v4-flash",
    requestModelId: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    displayName: "DeepSeek V4 Flash",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "deepseek-v4-flash-free",
    requestModelId: "deepseek-v4-flash-free",
    name: "DeepSeek V4 Flash Free",
    displayName: "DeepSeek V4 Flash Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "deepseek-v4-pro",
    requestModelId: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    displayName: "DeepSeek V4 Pro",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "gemini-3-flash",
    requestModelId: "gemini-3-flash",
    name: "Gemini 3 Flash",
    displayName: "Gemini 3 Flash",
    routeKind: "model_specific",
    apiFormat: "openai",
    contextWindow: 1048576,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gemini-3.1-pro",
    requestModelId: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    displayName: "Gemini 3.1 Pro",
    routeKind: "model_specific",
    apiFormat: "openai",
    contextWindow: 1048576,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gemini-3.5-flash",
    requestModelId: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    displayName: "Gemini 3.5 Flash",
    routeKind: "model_specific",
    apiFormat: "openai",
    contextWindow: 1048576,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gemini-3.5-flash-lite",
    requestModelId: "gemini-3.5-flash-lite",
    name: "Gemini 3.5 Flash Lite",
    displayName: "Gemini 3.5 Flash Lite",
    routeKind: "model_specific",
    apiFormat: "openai",
    contextWindow: 1048576,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gemini-3.6-flash",
    requestModelId: "gemini-3.6-flash",
    name: "Gemini 3.6 Flash",
    displayName: "Gemini 3.6 Flash",
    routeKind: "model_specific",
    apiFormat: "openai",
    contextWindow: 1048576,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gemini-3.7-flash",
    requestModelId: "gemini-3.7-flash",
    name: "Gemini 3.7 Flash",
    displayName: "Gemini 3.7 Flash",
    routeKind: "model_specific",
    apiFormat: "openai",
    contextWindow: 1048576,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "glm-5",
    requestModelId: "glm-5",
    name: "GLM 5",
    displayName: "GLM 5",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 202752,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "glm-5.1",
    requestModelId: "glm-5.1",
    name: "GLM 5.1",
    displayName: "GLM 5.1",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 202752,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "glm-5.2",
    requestModelId: "glm-5.2",
    name: "GLM 5.2",
    displayName: "GLM 5.2",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 202752,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "gpt-5",
    requestModelId: "gpt-5",
    name: "GPT 5",
    displayName: "GPT 5",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 128000,
    maxOutput: 16384,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5-codex",
    requestModelId: "gpt-5-codex",
    name: "GPT 5 Codex",
    displayName: "GPT 5 Codex",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 128000,
    maxOutput: 16384,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5-nano",
    requestModelId: "gpt-5-nano",
    name: "GPT 5 Nano",
    displayName: "GPT 5 Nano",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 128000,
    maxOutput: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "gpt-5.1",
    requestModelId: "gpt-5.1",
    name: "GPT 5.1",
    displayName: "GPT 5.1",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.1-codex",
    requestModelId: "gpt-5.1-codex",
    name: "GPT 5.1 Codex",
    displayName: "GPT 5.1 Codex",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.1-codex-max",
    requestModelId: "gpt-5.1-codex-max",
    name: "GPT 5.1 Codex Max",
    displayName: "GPT 5.1 Codex Max",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.1-codex-mini",
    requestModelId: "gpt-5.1-codex-mini",
    name: "GPT 5.1 Codex Mini",
    displayName: "GPT 5.1 Codex Mini",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.2",
    requestModelId: "gpt-5.2",
    name: "GPT 5.2",
    displayName: "GPT 5.2",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.2-codex",
    requestModelId: "gpt-5.2-codex",
    name: "GPT 5.2 Codex",
    displayName: "GPT 5.2 Codex",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.3-codex",
    requestModelId: "gpt-5.3-codex",
    name: "GPT 5.3 Codex",
    displayName: "GPT 5.3 Codex",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.3-codex-spark",
    requestModelId: "gpt-5.3-codex-spark",
    name: "GPT 5.3 Codex Spark",
    displayName: "GPT 5.3 Codex Spark",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.4",
    requestModelId: "gpt-5.4",
    name: "GPT 5.4",
    displayName: "GPT 5.4",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.4-mini",
    requestModelId: "gpt-5.4-mini",
    name: "GPT 5.4 Mini",
    displayName: "GPT 5.4 Mini",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.4-nano",
    requestModelId: "gpt-5.4-nano",
    name: "GPT 5.4 Nano",
    displayName: "GPT 5.4 Nano",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 32768,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.4-pro",
    requestModelId: "gpt-5.4-pro",
    name: "GPT 5.4 Pro",
    displayName: "GPT 5.4 Pro",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.5",
    requestModelId: "gpt-5.5",
    name: "GPT 5.5",
    displayName: "GPT 5.5",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.5-pro",
    requestModelId: "gpt-5.5-pro",
    name: "GPT 5.5 Pro",
    displayName: "GPT 5.5 Pro",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.6-luna",
    requestModelId: "gpt-5.6-luna",
    name: "GPT 5.6 Luna",
    displayName: "GPT 5.6 Luna",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 400000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.6-sol",
    requestModelId: "gpt-5.6-sol",
    name: "GPT 5.6 Sol",
    displayName: "GPT 5.6 Sol",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 400000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "gpt-5.6-terra",
    requestModelId: "gpt-5.6-terra",
    name: "GPT 5.6 Terra",
    displayName: "GPT 5.6 Terra",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 400000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "grok-build-0.1",
    requestModelId: "grok-build-0.1",
    name: "Grok Build 0.1",
    displayName: "Grok Build 0.1",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 131072,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "grok-4.5",
    requestModelId: "grok-4.5",
    name: "Grok 4.5",
    displayName: "Grok 4.5",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 500000,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "grok-4.6",
    requestModelId: "grok-4.6",
    name: "Grok 4.6",
    displayName: "Grok 4.6",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 500000,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "kimi-k2.5",
    requestModelId: "kimi-k2.5",
    name: "Kimi K2.5",
    displayName: "Kimi K2.5",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 262144,
    supportsTools: true,
    supportsVision: true,
    fixedTemperature: 1,
    supportsThinking: true,
  },
  {
    id: "kimi-k2.6",
    requestModelId: "kimi-k2.6",
    name: "Kimi K2.6",
    displayName: "Kimi K2.6",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 262144,
    supportsTools: true,
    supportsVision: true,
    fixedTemperature: 1,
    needsReasoningContentWorkaround: true,
    supportsThinking: true,
  },
  {
    id: "kimi-k2.7-code",
    requestModelId: "kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    displayName: "Kimi K2.7 Code",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 262144,
    supportsTools: true,
    supportsVision: true,
    fixedTemperature: 1,
    needsReasoningContentWorkaround: true,
    supportsThinking: true,
  },
  {
    id: "kimi-k3",
    requestModelId: "kimi-k3",
    name: "Kimi K3",
    displayName: "Kimi K3",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 1000000,
    maxOutput: 262144,
    supportsTools: true,
    supportsVision: true,
    fixedTemperature: 1,
    needsReasoningContentWorkaround: true,
    supportsThinking: true,
  },
  {
    id: "hy3-free",
    requestModelId: "hy3-free",
    name: "Hy3 Free",
    displayName: "Hy3 Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "laguna-s-2.1-free",
    requestModelId: "laguna-s-2.1-free",
    name: "Laguna S 2.1 Free",
    displayName: "Laguna S 2.1 Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "mimo-v2.5-free",
    requestModelId: "mimo-v2.5-free",
    name: "MiMo V2.5 Free",
    displayName: "MiMo V2.5 Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "minimax-m2.5",
    requestModelId: "minimax-m2.5",
    name: "MiniMax M2.5",
    displayName: "MiniMax M2.5",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 196608,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "minimax-m2.7",
    requestModelId: "minimax-m2.7",
    name: "MiniMax M2.7",
    displayName: "MiniMax M2.7",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 196608,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "minimax-m3",
    requestModelId: "minimax-m3",
    name: "MiniMax M3",
    displayName: "MiniMax M3",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 196608,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "muse-spark-1.2",
    requestModelId: "muse-spark-1.2",
    name: "Muse Spark 1.2",
    displayName: "Muse Spark 1.2",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 1048576,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
  {
    id: "nemotron-3-ultra-free",
    requestModelId: "nemotron-3-ultra-free",
    name: "Nemotron 3 Ultra Free",
    displayName: "Nemotron 3 Ultra Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "nemotron-3.5-lightning-free",
    requestModelId: "nemotron-3.5-lightning-free",
    name: "Nemotron 3.5 Lightning Free",
    displayName: "Nemotron 3.5 Lightning Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "qwen3.5-plus",
    requestModelId: "qwen3.5-plus",
    name: "Qwen3.5 Plus",
    displayName: "Qwen3.5 Plus",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: false,
    supportsThinking: true,
  },
  {
    id: "qwen3.6-plus",
    requestModelId: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    displayName: "Qwen3.6 Plus",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 1000000,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
    supportsThinking: true,
  },
];
