export type ZenRouteKind = "responses" | "messages" | "chat_completions" | "model_specific";
export type ZenApiFormat = "openai" | "anthropic";

export interface ZenModelInfo {
  id: string;
  requestModelId: string;
  name: string;
  displayName: string;
  routeKind: ZenRouteKind;
  apiFormat: ZenApiFormat;
  contextWindow: number;
  maxOutput: number;
  supportsTools: boolean;
  supportsVision: boolean;
  fixedTemperature?: number;
  reasoningEffort?: "xhigh" | "high" | "medium" | "low" | "minimal" | "none";
  needsReasoningContentWorkaround?: boolean;
}

// Models that do not actually support tool/function calling.
// These still declare toolCalling capability so they appear in the model picker,
// but the provider strips tools from requests before sending to the API.
export const NO_TOOL_MODEL_IDS = new Set([
  "big-pickle",
  "hy3-preview-free",
  "ling-2.6-flash-free",
  "minimax-m2.5-free",
  "nemotron-3-super-free",
]);

export const ZEN_MODEL_CATALOG: ZenModelInfo[] = [
  {
    id: "big-pickle",
    requestModelId: "big-pickle",
    name: "Big Pickle",
    displayName: "Big Pickle",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
  },
  {
    id: "minimax-m2.5",
    requestModelId: "minimax-m2.5",
    name: "MiniMax M2.5",
    displayName: "MiniMax M2.5",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 196608,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: false,
  },
  {
    id: "minimax-m2.5-free",
    requestModelId: "minimax-m2.5-free",
    name: "MiniMax M2.5 Free",
    displayName: "MiniMax M2.5 Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 196608,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
  },
  {
    id: "minimax-m2.7",
    requestModelId: "minimax-m2.7",
    name: "MiniMax M2.7",
    displayName: "MiniMax M2.7",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 196608,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: false,
  },
  {
    id: "claude-opus-4-7",
    requestModelId: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    displayName: "Claude Opus 4.7",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "claude-sonnet-4-6",
    requestModelId: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    displayName: "Claude Sonnet 4.6",
    routeKind: "messages",
    apiFormat: "anthropic",
    contextWindow: 200000,
    maxOutput: 64000,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "gpt-5.4",
    requestModelId: "gpt-5.4",
    name: "GPT 5.4",
    displayName: "GPT 5.4",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "gpt-5.4-mini",
    requestModelId: "gpt-5.4-mini",
    name: "GPT 5.4 Mini",
    displayName: "GPT 5.4 Mini",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "gpt-5.4-nano",
    requestModelId: "gpt-5.4-nano",
    name: "GPT 5.4 Nano",
    displayName: "GPT 5.4 Nano",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 32768,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "gpt-5.4-pro",
    requestModelId: "gpt-5.4-pro",
    name: "GPT 5.4 Pro",
    displayName: "GPT 5.4 Pro",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "gpt-5.5",
    requestModelId: "gpt-5.5",
    name: "GPT 5.5",
    displayName: "GPT 5.5",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "gpt-5.5-pro",
    requestModelId: "gpt-5.5-pro",
    name: "GPT 5.5 Pro",
    displayName: "GPT 5.5 Pro",
    routeKind: "responses",
    apiFormat: "openai",
    contextWindow: 272000,
    maxOutput: 128000,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "gemini-3-flash",
    requestModelId: "gemini-3-flash",
    name: "Gemini 3 Flash",
    displayName: "Gemini 3 Flash",
    routeKind: "model_specific",
    apiFormat: "openai",
    contextWindow: 1048576,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "gemini-3.1-pro",
    requestModelId: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    displayName: "Gemini 3.1 Pro",
    routeKind: "model_specific",
    apiFormat: "openai",
    contextWindow: 1048576,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
  },
  {
    id: "glm-5.1",
    requestModelId: "glm-5.1",
    name: "GLM 5.1",
    displayName: "GLM 5.1",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 202752,
    maxOutput: 131072,
    supportsTools: true,
    supportsVision: false,
  },
  {
    id: "hy3-preview-free",
    requestModelId: "hy3-preview-free",
    name: "Hy3 Preview Free",
    displayName: "Hy3 Preview Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
  },
  {
    id: "kimi-k2.6",
    requestModelId: "kimi-k2.6",
    name: "Kimi K2.6",
    displayName: "Kimi K2.6",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 262144,
    supportsTools: true,
    supportsVision: true,
    fixedTemperature: 1,
    needsReasoningContentWorkaround: true,
  },
  {
    id: "ling-2.6-flash-free",
    requestModelId: "ling-2.6-flash-free",
    name: "Ling 2.6 Flash Free",
    displayName: "Ling 2.6 Flash Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
  },
  {
    id: "nemotron-3-super-free",
    requestModelId: "nemotron-3-super-free",
    name: "Nemotron 3 Super Free",
    displayName: "Nemotron 3 Super Free",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 262144,
    maxOutput: 65536,
    supportsTools: false,
    supportsVision: false,
  },
  {
    id: "qwen3.6-plus",
    requestModelId: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    displayName: "Qwen3.6 Plus",
    routeKind: "chat_completions",
    apiFormat: "openai",
    contextWindow: 1000000,
    maxOutput: 65536,
    supportsTools: true,
    supportsVision: true,
  },
];
